# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

text_color_theme: ocean #eg: default | dark | forest | ocean | chocolate | orange
## Base settings ##
url: www.sindrilin.com
baseurl: /
title: sindrilin的小巢
description: 本站记录我在学习之旅的沿途风景

nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html

# paths:
#   base: /
#   home: /
#   all:  /all.html
#   rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
repository: sindrilin  #e.g. someone/someone.github.io
# repository_tree:  #e.g. master

## Language & timezone ##
lang: en #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Shanghai #see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## Author & social ##
author:
  name: sindrilin
  email: sindrilin@foxmail.com
  # facebook:  #your Facebook username
  # twitter:  #your Twitter username
  github:  sindrilin
  # googleplus:  #your Google+ username
  # weibo:  #your Weibo username
  # douban:  #your Douban username
  linkedin:  林同学

## TOC
toc:
  # selectors: 'h1,h2,h3'

## Comment system (Disqus) ##
disqus:
  # shortname:  #the Disqus shortname for the site

## Comment system (gitalk) ##
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  clientID: d718b31caa9b95ffcd44
  clientSecret: 16e80e5f6626d86e3273073d17448e7ed46914e2
  repository: gitalk-demo
  owner:  sindrilin
  admin: #Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
    - sindrilin

## Google Analytics ##
ga_tracking_id: UA-118054194-1

## Reading quantity (LeanCloud) ##
leancloud:
  app_id:  HS2TBMdGjF8Fpd6WSlBlOgw1-gzGzoHsz
  app_key:  SSPhP71AW5pnc4VbLe9nvRVs
  app_class:  blog_comment

mathjax: true
mathjax_autoNumber: true
mermaid: true
chart: true

## Paginate ##
paginate: 7
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: text # text | html

## Sources ##
# sources: bootcss #eg: bootcss | unpkg

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

