# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: "SindriLin的小巢"
title: SindriLin的小巢
brief-intro: 
description: "本站记录我iOS之旅的沿途风景"
baseurl: "http://sindrilin.com" # the subpath of your site, e.g. /blog
url: "http://sindrilin.com" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 
facebook_username: 
github_username:  JustKeepRunning
email: coderSindri@gmail.com
weibo_username: 2922715753
zhihu_username:
linkedIn_username: 欣达-林-78b390122
dribbble_username:

description_footer: 本站记录我iOS之旅的沿途风景！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: 
disqus_shortname: sindrilincom

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
cnzz_tongji: 1256664455

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6


